version: '3.8'

services:
  coursework-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Data Source=coursework.db"
      SeriLog__Path: "bin/Logs/log-.txt"
    restart: unless-stopped